vich_uploader:
    db_driver: orm

    mappings:
        block_image:
            uri_prefix: /uploads/images/blocks
            upload_destination: '%kernel.project_dir%/public/uploads/images/blocks/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false